source 'http://rubygems.org'

gem 'rails', :git => "git@github.com:phenomenal/rails.git"

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

#gem 'mysql2'
gem 'haml'
gem 'sqlite3'
gem 'phenomenal', :git => "git@git.phenomenal-gem.com:phenomenal.git"
# Gems used only for assets and not required
# in production environments by default.
#group :assets do
#  gem 'sass-rails'
#  gem 'coffee-rails'
#  gem 'uglifier'
#  gem 'yui-compressor'
#  gem 'execjs'
#  gem "therubyracer", :require => 'v8'
#end

#gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
group :development do
  gem 'rspec-rails'
  gem 'annotate-models'
end

group :test do
  gem 'rspec-rails'
  gem 'webrat'
end
